//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QCPatch.h"

@class NSTrackingArea, QCBooleanPort, QCIndexPort;

@interface FBCursorPatch : QCPatch
{
    QCIndexPort *inputStyle;
    QCBooleanPort *inputHide;
    BOOL _hasFocus;
    NSTrackingArea *_trackingAreaForWindow;
    NSTrackingArea *_trackingAreaForFullScreen;
    id _didEnterFullScreenObserver;
    id _didExitFullScreenObserver;
    id _didResignMainObserver;
    id _didBecomeMainObserver;
    id _didResignActiveObserver;
}

+ (int)timeModeWithIdentifier:(id)arg1;
+ (int)executionModeWithIdentifier:(id)arg1;
+ (BOOL)allowsSubpatchesWithIdentifier:(id)arg1;
@property(retain, nonatomic) id didResignActiveObserver; // @synthesize didResignActiveObserver=_didResignActiveObserver;
@property(retain, nonatomic) id didBecomeMainObserver; // @synthesize didBecomeMainObserver=_didBecomeMainObserver;
@property(retain, nonatomic) id didResignMainObserver; // @synthesize didResignMainObserver=_didResignMainObserver;
@property(retain, nonatomic) id didExitFullScreenObserver; // @synthesize didExitFullScreenObserver=_didExitFullScreenObserver;
@property(retain, nonatomic) id didEnterFullScreenObserver; // @synthesize didEnterFullScreenObserver=_didEnterFullScreenObserver;
@property(retain, nonatomic) NSTrackingArea *trackingAreaForFullScreen; // @synthesize trackingAreaForFullScreen=_trackingAreaForFullScreen;
@property(retain, nonatomic) NSTrackingArea *trackingAreaForWindow; // @synthesize trackingAreaForWindow=_trackingAreaForWindow;
- (void).cxx_destruct;
- (void)mouseMoved:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateCursorStyle;
- (void)disable:(id)arg1;
- (void)trackFullScreenViewer;
- (void)enable:(id)arg1;
- (id)initWithIdentifier:(id)arg1;

@end

