//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDocument, NSMutableDictionary;

@interface FBOInteractionController : NSObject
{
    BOOL _shouldKeepTraversing;
    NSMutableDictionary *_hitPatches;
    NSMutableDictionary *_downPoints;
    NSMutableDictionary *_lastTouchPoints;
    NSDocument *_document;
    struct CGSize _viewerSize;
}

+ (id)controllerForDocument:(id)arg1;
+ (id)controllerForPatch:(id)arg1;
+ (void)initialize;
@property BOOL shouldKeepTraversing; // @synthesize shouldKeepTraversing=_shouldKeepTraversing;
@property(nonatomic) __weak NSDocument *document; // @synthesize document=_document;
@property(retain, nonatomic) NSMutableDictionary *lastTouchPoints; // @synthesize lastTouchPoints=_lastTouchPoints;
@property(retain, nonatomic) NSMutableDictionary *downPoints; // @synthesize downPoints=_downPoints;
@property(retain, nonatomic) NSMutableDictionary *hitPatches; // @synthesize hitPatches=_hitPatches;
@property struct CGSize viewerSize; // @synthesize viewerSize=_viewerSize;
- (void).cxx_destruct;
- (BOOL)patchIsUberSprite:(id)arg1;
- (BOOL)patchIsDevice:(id)arg1;
- (BOOL)shouldHitTestSprite:(id)arg1;
- (struct CGSize)sizeForSprite:(id)arg1;
- (BOOL)hitTestPoint:(struct CGPoint)arg1 inSize:(struct CGSize)arg2;
- (struct CGPoint)transformPoint:(struct CGPoint)arg1 toDevicePatch:(id)arg2;
- (struct CGPoint)transformPoint:(struct CGPoint)arg1 toSprite:(id)arg2;
- (void)traverseSubpatchesOfPatch:(id)arg1 withPoint:(struct CGPoint)arg2 successArray:(id)arg3;
- (BOOL)hitTestGraphWithPoint:(struct CGPoint)arg1 iteration:(unsigned long long)arg2;
- (BOOL)hitTestPatch:(id)arg1 withPoint:(struct CGPoint)arg2 iteration:(unsigned long long)arg3;

@end

