//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBODynamicPortsPatch.h"

@class QCIndexPort;

@interface FBOMultiSwitchPatch : FBODynamicPortsPatch
{
    QCIndexPort *outputIndex;
    unsigned long long _inputCount;
}

+ (int)timeModeWithIdentifier:(id)arg1;
+ (Class)inspectorClassWithIdentifier:(id)arg1;
+ (int)executionModeWithIdentifier:(id)arg1;
+ (BOOL)allowsSubpatchesWithIdentifier:(id)arg1;
+ (id)stateKeysWithIdentifier:(id)arg1;
@property(nonatomic) unsigned long long inputCount; // @synthesize inputCount=_inputCount;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_removePortNumber:(unsigned long long)arg1;
- (id)_addPortNumber:(unsigned long long)arg1;
- (BOOL)execute:(id)arg1 time:(double)arg2 arguments:(id)arg3;
- (id)initWithIdentifier:(id)arg1;

@end

