//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QCPatch.h"

@class QCNumberPort, QCStringPort;

@interface FBRGBToHex : QCPatch
{
    QCNumberPort *inputRed;
    QCNumberPort *inputGreen;
    QCNumberPort *inputBlue;
    QCStringPort *outputHex;
}

+ (int)timeModeWithIdentifier:(id)arg1;
+ (int)executionModeWithIdentifier:(id)arg1;
+ (BOOL)allowsSubpatchesWithIdentifier:(id)arg1;
- (void).cxx_destruct;
- (BOOL)execute:(id)arg1 time:(double)arg2 arguments:(id)arg3;

@end

