//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class FBSafariSegmentedCell, NSButton, NSImage, NSImageView, NSSegmentedControl, NSString, NSTextField, NSToolbar;

@interface FBSafariToolbarController : NSViewController
{
    BOOL _forwardDown;
    BOOL _backDown;
    NSToolbar *_toolbar;
    NSTextField *_textField;
    NSButton *_downloadsButton;
    NSSegmentedControl *_backForwardButtons;
    FBSafariSegmentedCell *_segmentedCell;
    NSImageView *_faviconView;
    NSImage *_faviconImage;
    NSString *_URL;
}

+ (id)controllerForQCView:(id)arg1;
@property BOOL backDown; // @synthesize backDown=_backDown;
@property BOOL forwardDown; // @synthesize forwardDown=_forwardDown;
@property(copy, nonatomic) NSString *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) NSImage *faviconImage; // @synthesize faviconImage=_faviconImage;
@property(retain, nonatomic) NSImageView *faviconView; // @synthesize faviconView=_faviconView;
@property FBSafariSegmentedCell *segmentedCell; // @synthesize segmentedCell=_segmentedCell;
@property NSSegmentedControl *backForwardButtons; // @synthesize backForwardButtons=_backForwardButtons;
@property NSButton *downloadsButton; // @synthesize downloadsButton=_downloadsButton;
@property NSTextField *textField; // @synthesize textField=_textField;
@property NSToolbar *toolbar; // @synthesize toolbar=_toolbar;
- (void).cxx_destruct;
- (void)setURLLabel:(id)arg1;
- (void)setFaviconGraphic:(id)arg1;
- (void)loadView;

@end

