//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QCPatch.h"

@class FBSafariToolbarController, NSString, NSToolbar, NSWindow, QCBooleanPort, QCImagePort, QCStringPort;

@interface FBSafariTheme : QCPatch
{
    QCStringPort *inputWindowTitle;
    QCStringPort *inputURL;
    QCImagePort *inputFavicon;
    QCBooleanPort *inputBackEnabled;
    QCBooleanPort *inputForwardEnabled;
    FBSafariToolbarController *_toolbarController;
    NSToolbar *_cachedToolbar;
    NSString *_cachedWindowTitle;
    NSWindow *_cachedViewerWindow;
    unsigned long long _cachedCollectionBehavior;
}

+ (int)timeModeWithIdentifier:(id)arg1;
+ (int)executionModeWithIdentifier:(id)arg1;
+ (BOOL)allowsSubpatchesWithIdentifier:(id)arg1;
@property unsigned long long cachedCollectionBehavior; // @synthesize cachedCollectionBehavior=_cachedCollectionBehavior;
@property(nonatomic) __weak NSWindow *cachedViewerWindow; // @synthesize cachedViewerWindow=_cachedViewerWindow;
@property(copy, nonatomic) NSString *cachedWindowTitle; // @synthesize cachedWindowTitle=_cachedWindowTitle;
@property(retain, nonatomic) NSToolbar *cachedToolbar; // @synthesize cachedToolbar=_cachedToolbar;
@property(retain, nonatomic) FBSafariToolbarController *toolbarController; // @synthesize toolbarController=_toolbarController;
- (void).cxx_destruct;
- (void)_fetchActualFavicon;
- (id)viewerWindow;
- (void)restoreViewerChrome;
- (void)disable:(id)arg1;
- (BOOL)execute:(id)arg1 time:(double)arg2 arguments:(id)arg3;
- (void)browserifyViewerChrome;
- (void)enable:(id)arg1;
- (id)initWithIdentifier:(id)arg1;

@end

