//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocument.h"

@interface NSDocument (FBAdditions)
- (id)fb_graph;
- (id)fb_patchView;
- (id)fb_editorView;
@end

