//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenu.h"

@interface NSMenu (FBAdditions)
- (id)addItemWithTitle:(id)arg1 keyEquivalent:(id)arg2 target:(id)arg3 action:(SEL)arg4 state:(BOOL)arg5;
@end

