//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (AMAssociatedObjects)
- (id)associatedValueForKey:(void *)arg1;
- (void)weaklyAssociateValue:(id)arg1 withKey:(void *)arg2;
- (void)associateValue:(id)arg1 withKey:(void *)arg2;
@end

