//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QCPatch.h"

@interface QCPatch (FBAdditions)
- (id)description;
- (id)fb_className;
- (id)fb_classNameForNode;
- (id)fb_name;
- (void)fb_setActorPosition:(struct CGPoint)arg1;
- (struct CGPoint)fb_actorPosition;
- (struct CGSize)fb_actorSizeInKeyPatchView;
- (struct CGSize)fb_actorSize;
- (id)fb_actor;
- (struct CGSize)fb_cachedActorSize;
- (id)fb_document;
- (id)fb_rootPatch;
@end

