//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QCPatchView.h"

@interface QCPatchView (FBAdditions)
- (id)fb_selectedPatch;
- (BOOL)fb_addPatch:(id)arg1;
- (void)fb_setSelected:(BOOL)arg1 forPatch:(id)arg2;
- (id)fb_positionValueForPatchWithPort:(id)arg1 alignedToPort:(id)arg2;
- (struct CGPoint)fb_positionForPatchWithPort:(id)arg1 alignedToPort:(id)arg2;
@end

