//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QCPort.h"

@interface QCPort (FBAdditions)
- (id)fb_name;
- (BOOL)fb_isInputPort;
- (id)fb_connectedPorts;
@end

